Appraise/urls.py
"""
Appraise evaluation framework

See LICENSE for usage details
"""
# pylint: disable=unused-import,import-error
from django.conf.urls import handler404
from django.conf.urls import handler500
from django.conf.urls import include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import re_path

from Appraise.settings import BASE_CONTEXT
from Appraise.settings import DEBUG
from Campaign import views as campaign_views
from Dashboard import views as dashboard_views
from EvalData import views as evaldata_views
from EvalView import views as evalview_views


# HTTP error handlers
# pylint: disable=invalid-name
handler404 = 'Dashboard.views._page_not_found'

handler500 = 'Dashboard.views._server_error'

urlpatterns = [
    re_path(
        r'^admin/taskagenda/reset/(?P<agenda_id>[0-9]+)/$',
        evaldata_views.reset_taskagenda,
        name='reset-taskagenda',
    ),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', dashboard_views.frontpage, name='frontpage'),
    re_path(
        r'^dashboard/create-profile/$',
        dashboard_views.create_profile,
        name='create-profile',
    ),
    re_path(
        r'^dashboard/sign-in/$',
        auth_views.LoginView.as_view(
            template_name='Dashboard/signin.html',
            extra_context=BASE_CONTEXT,
        ),
        name='sign-in',
    ),
    re_path(
        (
            r'^dashboard/sso/(?P<username>[a-zA-Z0-9]{10,20})/'
            r'(?P<password>[a-fA-F0-9]{8})/$'
        ),
        dashboard_views.sso_login,
    ),
    re_path(
        r'^dashboard/sign-out/$',
        auth_views.LogoutView.as_view(
            template_name='Dashboard/signout.html',  # TODO: this does not exist!
            extra_context=BASE_CONTEXT,
        ),
        name='sign-out',
    ),
    re_path(
        r'^dashboard/change-password/$',
        auth_views.PasswordChangeView.as_view(
            template_name='Dashboard/change-password.html',
            success_url='/dashboard/',
            extra_context=BASE_CONTEXT,
        ),
        name='change-password',
    ),
    re_path(
        r'^dashboard/update-profile/$',
        dashboard_views.update_profile,
        name='update-profile',
    ),  # TODO: remove?
    re_path(r'^dashboard/$', dashboard_views.dashboard, name='dashboard'),
    re_path(
        r'^data-assessment/$',
        evalview_views.data_assessment,
        name='data-assessment',
    ),
    re_path(
        r'^data-assessment/(?P<code>[a-z]{3})/$',
        evalview_views.data_assessment,
        name='data-assessment',
    ),
    re_path(
        r'^data-assessment/(?P<code>[a-z]{3})/' r'(?P<campaign_name>[a-zA-Z0-9]+)/$',
        evalview_views.data_assessment,
        name='data-assessment',
    ),
    re_path(
        r'^direct-assessment/$',
        evalview_views.direct_assessment,
        name='direct-assessment',
    ),
    re_path(
        r'^direct-assessment/(?P<code>[a-z]{3})/$',
        evalview_views.direct_assessment,
        name='direct-assessment',
    ),
    re_path(
        r'^direct-assessment/(?P<code>[a-z]{3})/' r'(?P<campaign_name>[a-zA-Z0-9]+)/$',
        evalview_views.direct_assessment,
        name='direct-assessment',
    ),
    re_path(
        r'^direct-assessment-context/$',
        evalview_views.direct_assessment_context,
        name='direct-assessment-context',
    ),
    re_path(
        r'^direct-assessment-context/(?P<code>[a-z]{3})/$',
        evalview_views.direct_assessment_context,
        name='direct-assessment-context',
    ),
    re_path(
        r'^direct-assessment-context/(?P<code>[a-z]{3})/'
        r'(?P<campaign_name>[a-zA-Z0-9]+)/$',
        evalview_views.direct_assessment_context,
        name='direct-assessment-context',
    ),
    re_path(
        r'^direct-assessment-document/$',
        evalview_views.direct_assessment_document,
        name='direct-assessment-document',
    ),
    re_path(
        r'^direct-assessment-document/(?P<code>[a-z]{3})/$',
        evalview_views.direct_assessment_document,
        name='direct-assessment-document',
    ),
    re_path(
        r'^direct-assessment-document/(?P<code>[a-z]{3})/'
        r'(?P<campaign_name>[a-zA-Z0-9]+)/$',
        evalview_views.direct_assessment_document,
        name='direct-assessment-document',
    ),
    re_path(
        r'^multimodal-assessment/$',
        evalview_views.multimodal_assessment,
        name='multimodal-assessment',
    ),
    re_path(
        r'^multimodal-assessment/(?P<code>[a-z]{3})/$',
        evalview_views.multimodal_assessment,
        name='multimodal-assessment',
    ),
    re_path(
        r'^multimodal-assessment/(?P<code>[a-z]{3})/'
        r'(?P<campaign_name>[a-zA-Z0-9]+)/$',
        evalview_views.multimodal_assessment,
        name='multimodal-assessment',
    ),
    re_path(
        r'^pairwise-assessment/$',
        evalview_views.pairwise_assessment,
        name='pairwise-assessment',
    ),
    re_path(
        r'^pairwise-assessment/(?P<code>[a-z]{3})/$',
        evalview_views.pairwise_assessment,
        name='pairwise-assessment',
    ),
    re_path(
        r'^pairwise-assessment/(?P<code>[a-z]{3})/'
        r'(?P<campaign_name>[a-zA-Z0-9]+)/$',
        evalview_views.pairwise_assessment,
        name='pairwise-assessment',
    ),
    re_path(
        r'^pairwise-assessment-document/$',
        evalview_views.pairwise_assessment_document,
        name='pairwise-assessment-document',
    ),
    re_path(
        r'^pairwise-assessment-document/(?P<code>[a-z]{3})/$',
        evalview_views.pairwise_assessment_document,
        name='pairwise-assessment-document',
    ),
    re_path(
        r'^pairwise-assessment-document/(?P<code>[a-z]{3})/'
        r'(?P<campaign_name>[a-zA-Z0-9]+)/$',
        evalview_views.pairwise_assessment_document,
        name='pairwise-assessment-document',
    ),
    re_path(
        r'^campaign-status/(?P<campaign_name>[a-zA-Z0-9]+)/'
        r'(?P<sort_key>[0123456])?/?$',
        campaign_views.campaign_status,
        name='campaign_status',
    ),
]

if DEBUG:
    try:
        import debug_toolbar  # type: ignore

        urlpatterns = [
            re_path(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns  # type: ignore

    except ImportError:
        pass

Dashboard/models.py
"""
Appraise evaluation framework

See LICENSE for usage details
"""
from uuid import uuid4

from django.contrib.auth.models import Group
from django.contrib.auth.models import User
from django.db import models
from django.db.utils import OperationalError
from django.db.utils import ProgrammingError

# pylint: disable=import-error

LANGUAGE_CODES_AND_NAMES = {
    'aeb': 'Tunisian Arabic (تونسي)',
    'ces': 'Czech (čeština)',
    'zho': 'Chinese (中文)',
    'eng': 'English',
    'fin': 'Finnish (suomi)',
    'deu': 'German (Deutsch)',
    'lav': 'Latvian (latviešu)',
    'rus': 'Russian (русский)',
    'trk': 'Turkish (Türkçe)',
    'fra': 'French (français)',
    'hun': 'Hungarian (magyar)',
    'plk': 'Polish (polski)',
    'por': 'Portuguese (português)',
    'ron': 'Romanian (română)',
    'spa': 'Spanish (español)',
    'swe': 'Swedish (svenska)',
    'ara': 'Arabic (العربية)',
    'ita': 'Italian (italiano)',
    'jpn': 'Japanese (日本語)',
    'kor': 'Korean (한국어)',
    'nob': 'Norwegian (Bokmål)',
    'nld': 'Dutch (Nederlands)',
    'cat': 'Catalan (català)',
    'dan': 'Danish (dansk)',
    'hin': 'Hindi (हिन्दी)',
    'tha': 'Thai (ภาษาไทย)',
    'ben': 'Bengali (বাংলা)',
    'slk': 'Slovak (slovenčina)',
    'slv': 'Slovenian (slovenščina)',
    'est': 'Estonian (eesti)',
    'bul': 'Bulgarian (български)',
    'ell': 'Greek (ελληνικά)',
    'heb': 'Hebrew (עברית)',
    'cym': 'Welsh (Cymraeg)',
    'ukr': 'Ukrainian (українська)',
    'tel': 'Telugu (తెలుగు)',
    'tam': 'Tamil (தமிழ்)',
    'isl': 'Icelandic (íslenska)',
    'hrv': 'Croatian (hrvatski)',
    'lit': 'Lithuanian (lietuvių)',
    'vie': 'Vietnamese (tiếng Việt)',
    'srp': 'Serbian (srpski)',
    'bos': 'Bosnian (bosanski)',
    'ind': 'Indonesian (bahasa Indonesia)',
    'urd': 'Urdu (اُردُو)',
    'acm': 'Iraqi Arabic (راقي - ʕirāgi)',
    'ary': 'Moroccan Arabic (الدارجة - Darija)',
    'ayl': 'Libyan Arabic ( ليبي - lībi)',
    'ayn': 'Yemeni Arabic (يمني - yamani)',
    'fas': 'Farsi (فارسی)',
    'afr': 'Afrikaans',
    'mlt': 'Maltese (Malti)',
    'sin': 'Sinhalese (සිංහල sinhala)',
    'smo': 'Samoan (Gagana faʻa Sāmoa)',
    'mlg': 'Malagasy',
    'swa': 'Swahili (Kiswahili)',
    'fij': 'Fijian (Na Vosa Vakaviti)',
    'ton': 'Tongan (lea faka-Tonga)',
    'guj': 'Gujarati (ગુજરાતી)',
    'kaz': 'Kazakh (қазақша)',
    'zsm': 'Malaysian (bahasa Malaysia)',
    'hat': 'Haitian Creole (kreyòl ayisyen)',
    'fil': 'Filipino (Wikang Filipino)',
    'tah': 'Tahitian (Reo Tahiti)',
    'mri': 'Maori (Te reo Māori)',
    'pan': 'Punjabi (ਪੰਜਾਬੀ)',
    'kan': 'Kannada (ಕನ್ನಡ)',
    'mal': 'Malayalam (മലയാളം)',
    'mar': 'Marathi (मराठी)',
    'kat': 'Georgian (ქართული)',
    'gle': 'Irish (Gaeilge)',
    'zho-Hans': 'Simplified Chinese (中文 - 简化字)',
    'zho-Hant': 'Traditional Chinese (中文 - 正體字/繁體字)',
    'srp-Cyrl': 'Serbian (српски)',
    'srp-Latn': 'Serbian (srpski)',
    'asm': 'Assamese (অসমীয়া)',
    'ori': 'Odia (ଓଡ଼ିଆ)',
    'aze': 'Azerbaijani (Azeri)',
    'amh': 'Amharic (አማርኛ)',
    'sqi': 'Albanian (shqip)',
    'jav': 'Javanese (ꦧꦱꦗꦮ)',
    'sun': 'Sundanese (Basa Sunda)',
    'hau': 'Hausa (Harshen/Halshen Hausa)',
    'glg': 'Galician (galego)',
    'mya': 'Myanmar (မြန်မာစာ)',
    'ceb': 'Cebuano (Bisayâ)',
    'bel': 'Belarusian (беларуская мова)',
    'xho': 'Xhosa (isiXhosa)',
    'uzb': 'Uzbek (o‘zbekcha)',
    'ltz': 'Luxembourgish (Lëtzebuergesch)',
    'lao': 'Lao (ພາສາລາວ)',
    'khm': 'Khmer (ភាសាខ្មែរ)',
    'eus': 'Basque (euskara)',
    'hye': 'Armenian (հայերեն hayeren)',
    'mon': 'Mongolian (монгол хэл)',
    'mkd': 'Macedonian (македонски)',
    'som': 'Somali (Af Soomaali)',
    'tgk': 'Tajik (тоҷикӣ)',
    'kir': 'Kyrgyz (кыргыз)',
    'yid': 'Yiddish (ייִדיש)',
    'gla': 'Scottish Gaelic (Gàidhlig)',
    'epo': 'Esperanto',
    'lat': 'Latin (lingua latīna)',
    'yor': 'Yoruba (Èdè Yorùbá)',
    'zul': 'Zulu (isiZulu)',
    'ibo': 'Igbo (Asụsụ Igbo)',
    'tat': 'Tatar (татар теле)',
    'snd': 'Sindhi (سنڌي)',
    'nya': 'Chichewa (Nyanja)',
    'fry': 'Frisian (Frysk)',
    'sna': 'Shona (chiShona)',
    'bak': 'Bashkir (Башҡортса)',
    'prs': 'Dari (دری)',
    'haw': 'Hawaiian (ʻŌlelo Hawaiʻi)',
    'sot': 'Sotho (Sesotho)',
    'mhr': 'Meadow Mari (олыкмарла)',
    'pap': 'Papiamento (Papiamentu)',
    'udm': 'Udmurt (удмурт кыл)',
    'cos': 'Corsican (corsu)',
    'mrj': 'Hill Mari (Кырык мары йӹлмӹ)',
    'uig': 'Uyghur (ئۇيغۇر تىلى)',
    'wuu': 'Wu (吴语)',
    'pcm': 'Nigerian Pidgin',
    'tuk': 'Turkmen (Türkmençe)',
    'srd': 'Sardinian (sardu)',
    'hak': 'Hakka (客家话)',
    'hsn': 'Xiang (湘语)',
    'orm': 'Oromo (Afaan Oromoo)',
    'tsn': 'Tswana (Setswana)',
    'bew': 'Betawi (bahasa Betawi)',
    'gan': 'Gan (赣语)',
    'kin': 'Rwanda (Ikinyarwanda)',
    'shi': 'Shilha (ⵜⴰⵛⵍⵃⵉⵢⵜ)',
    'ace': 'Acehnese (Basa Acèh)',
    'quc': "K'iche' (Qatzijobʼal)",
    'ssw': 'Swazi (siSwati)',
    'ast': 'Asturian (asturianu)',
    'iku': 'Inuktitut (ᐃᓄᒃᑎᑐᑦ)',
    'bre': 'Breton (brezhoneg)',
    'oji': 'Ojibwe (Anishinaabemowin)',
    'hsb': 'Upper Sorbian (hornjoserbšćina)',
    'chr': 'Cherokee (ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ)',
    'lkt': 'Lakota (Lakȟótiyapi)',
    'ikt': 'Inuinnaqtun',
    'qwe': 'Quechua (Runasimi)',
    'tir': 'Tigrinya (ትግርኛ)',
    'wol': 'Wolof',
    'ewe': 'Ewe (Èʋegbe)',
    'fuc': 'Pulaar (Futa Tooro)',
    'bem': 'Bemba (Chibemba)',
    'mey': 'Hassaniya (حسانية)',
    'kok': 'Konkani (कोंकणी)',
    'nde': 'Ndebele (isiNdebele saseNyakatho)',
    'ven': 'Tshivenda (Tshivenḓa)',
    'bod': 'Tibetan (བོད་སྐད)',
    'oss': 'Ossetian (ирон ӕвзаг)',
    'ble': 'Balanta',
    'sag': 'Sango (yângâ tî sängö)',
    'div': 'Dhivehi (ދިވެހި)',
    'ogb': 'Ogbia (Ogbinya)',
    'dzo': 'Dzongkha (རྫོང་ཁ་)',
    'tpi': 'Tok Pisin',
    'oci': "Occitan (lenga d'òc)",
    'crs': 'Seychellois Creole (kreol, seselwa)',
    'fao': 'Faroese (føroyskt mál)',
    'amu': 'Amuzgo (Ñomndaa)',
    'agr': 'Aguaruna (Awajún)',
    'jiv': 'Shuar (Šiwar čičam)',
    'axk': 'Aka (Yaka)',
    'sme': 'Northern Sami (davvisámegiella)',
    'ppk': 'Uma (Pipikoro)',
    'arg': 'Aragonese (aragonés)',
    'bis': 'Bislama (Bichelamar)',
    'dsb': 'Lower Sorbian (dolnoserbšćina)',
    'acu': 'Achuar (Shiwiar)',
    'soq': 'Sona (Kanasi)',
    'usp': 'Uspantek (Uspanteco)',
    'bbg': 'Barama (Varama)',
    'kmr': 'Kurmanji (Kurmancî)',
    'ckb': 'Sorani (کوردیی ناوەندی)',
    'nep': 'Nepali (नेपाली)',
    'yue': 'Cantonese (廣東話)',
    'apc': 'Levantine Arabic (اللَّهْجَةُ الشَّامِيَّة)',
    'arz': 'Egyptian Arabic (اللهجه المصريه)',
    'afb': 'Gulf Arabic (خليجي)',
    'mww': 'Hmong Daw',
    'otq': 'Querétaro Otomi',
    'tlh': 'Klingon (tlhIngan Hol)',
    'yua': 'Yucatec Maya (mayaʼ tʼàan)',
    'pus': 'Pashto (پښتو)',
    'lzh': 'Classical Chinese (文言文)',
    'chv': 'Chuvash (Чӑвашла)',
    'lin': 'Lingala (Lingála)',
    'lug': 'Luganda (Oluganda)',
    'sgg': 'Swiss-German Sign Language (Deutschschweizer Gebärdensprache (DSGS))',
    'liv': 'Livonian (līvõ kēļ)',
    'sah': 'Yakut (саха тыла)',
}

# All sign language codes
SIGN_LANGUAGE_CODES = set([LANGUAGE_CODES_AND_NAMES['sgg']])

# Ensure that all languages have a corresponding group.
try:
    for code in LANGUAGE_CODES_AND_NAMES:
        if not Group.objects.filter(name=code).exists():
            new_language_group = Group(name=code)
            new_language_group.save()

except (OperationalError, ProgrammingError):
    pass


def validate_language_code(code_or_codes):
    """
    Validates given language code string or list of code strings.

    Returns True if valid, False otherwise.
    """
    valid_codes = [x.lower() for x in LANGUAGE_CODES_AND_NAMES]
    valid = False
    if isinstance(code_or_codes, (list, tuple)):
        valid = all([x.lower() in valid_codes for x in code_or_codes])

    else:
        valid = code_or_codes.lower() in valid_codes

    return valid


def create_uuid4_token():
    """
    Creates a new UUID4-based token.
    """
    return uuid4().hex[:8]


# pylint: disable=C0330,E1101,too-few-public-methods
class UserInviteToken(models.Model):
    """
    User invite tokens allowing to register an account.
    """

    group = models.ForeignKey(Group, models.PROTECT, db_index=True)

    user = models.ForeignKey(User, models.PROTECT, db_index=True, blank=True, null=True)

    token = models.CharField(
        max_length=8,
        db_index=True,
        default=create_uuid4_token,
        unique=True,
        help_text="Unique invite token",
        verbose_name="Invite token",
    )

    active = models.BooleanField(
        db_index=True,
        default=True,
        help_text="Indicates that this invite can still be used.",
        verbose_name="Active?",
    )

    class Meta:
        """
        Metadata options for the UserInviteToken object model.
        """

        verbose_name = "User invite token"
        verbose_name_plural = "User invite tokens"

    def __str__(self):
        """
        Returns a Unicode String for this UserInviteToken object.
        """
        return u'<user-invite id="{0}" token="{1}" active="{2}" group="{3}" />'.format(
            self.id, self.token, self.active, self.group.name
        )


# pylint: disable=too-few-public-methods
class TimedKeyValueData(models.Model):
    """
    Stores a simple (key, value) pair.
    """

    key = models.CharField(max_length=100, blank=False, null=False)
    value = models.TextField(blank=False, null=False)
    date_and_time = models.DateTimeField(
        blank=False, null=False, editable=False, auto_now_add=True
    )

    @classmethod
    def update_status_if_changed(cls, key, new_value):
        """
        Stores a new TimedKeyValueData instance if value for key has changed
        """
        _latest_values = cls.objects.filter(key=key)
        _latest_values = _latest_values.order_by('date_and_time').reverse()
        _latest_values = _latest_values.values_list('value', flat=True)

Dashboard/templates/Dashboard/change-password.html
{% extends "Dashboard/base.html" %}
{% load i18n static %}

{% block content %}

  {% if form.errors %}
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <p><strong>Warning!</strong> Your passwords did not match. Please try again.</p>
  </div>

  {% endif %}

  <div class="page-header">
    <h1>Password change</h1>
    <p>Please enter your old password once and the desired new password twice so we can verify you typed it in correctly.</p>
    
    <div class="panel panel-primary" style="margin-top: 20px;">
      <div class="panel-heading">
        <h3 class="panel-title"><strong>Note</strong></h3>
      </div>
      <div class="panel-body">
        <p>After submitting this form you will be redirected to your dashboard. If successful your current session will continue. No confirmation message will be shown. If you provided a wrong value for the old password field or typed in two different new passwords, you will see an error message and your old password remains unchanged.</p>
      </div>
    </div>
  </div>
  <form class="form-horizontal" method="post" action="{% url 'change-password' %}">
  {% csrf_token %}

   <div class="form-group">
      <label for="id_old_password" class="col-sm-4 control-label">Old password</label>
      <div class="col-sm-4">
        <div class="input-group">
          <div class="input-group-addon">required</div>
          <input class="form-control" name="old_password" id="id_old_password" type="password" />
        </div>
        <p class="help-block">Please authenticate with your old password</p>
      </div>
    </div>

    <div class="form-group">
      <label for="id_new_password1" class="col-sm-4 control-label">New password</label>
      <div class="col-sm-4">
        <div class="input-group">
          <div class="input-group-addon">required</div>
          <input class="form-control" name="new_password1" id="new_password1" type="password" />
        </div>
        <p class="help-block">Please enter your new password</p>
        <ul class="help-block">
          <li><small>Can't be too similar to your other personal information;</small></li>
          <li><small>Must contain at least 8 characters;</small></li>
          <li><small>Can't be a commonly used password;</small></li>
          <li><small>Can't be entirely numeric.</small></li>
        </ul>
      </div>
    </div>

    <div class="form-group">
      <label for="id_new_password2" class="col-sm-4 control-label">New password (again)</label>
      <div class="col-sm-4">
        <div class="input-group">
          <div class="input-group-addon">required</div>
          <input class="form-control" name="new_password2" id="id_new_password2" type="password" />
        </div>
        <p class="help-block">Please re-type your new password</p>
      </div>
    </div>

    <button type="submit" class="col-sm-offset-4 btn btn-primary">Change password</button>
  
  </form>
{% endblock %}

Dashboard/templates/Dashboard/create-profile.html
{% extends "Dashboard/base.html" %}

{% block content %}
  {% if errors %}
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {% if 'invalid_username' in errors %}
    <p><strong>Warning!</strong> Invalid or missing username. Please provide a new username.</p>
    {% elif 'invalid_email' in errors %}
    <p><strong>Warning!</strong> Invalid or missing email address. Please provide your email address. It will never be shared.</p>
    {% elif 'invalid_token' in errors %}
    <p><strong>Warning!</strong> Invalid or inactive invite token. Please try again and contact your team lead if the problem persists.</p>
    {% elif 'invalid_languages' in errors %}
    <p><strong>Warning!</strong> Invalid or missing language selection. Please choose at least one target language for evaluation.</p>
    {% else %}
    <p><strong>Warning!</strong> Something bad happened. Please try again.</p>
    {% endif %}
  </div>
  {% endif %}

  <div class="page-header">
    <h1>Create profile</h1>
    <p>Please enter your desired username, your email address and your unique invite token. Then, tell us which target languages you can evaluate.</p>
    
    <div class="panel panel-primary" style="margin-top: 20px;">
      <div class="panel-heading">
        <h3 class="panel-title"><strong>Note</strong></h3>
      </div>
      <div class="panel-body">
        <p>Each invite token can only be used once. After submitting this form you will be redirected to the front page. If successful you will be automatically logged into a new browser session. No confirmation message will be shown. If you provided a wrong value for the invite token field you will see an error message.</p>
      </div>
    </div>
  </div>
  <form class="form-horizontal" method="post" action="{% url 'create-profile' %}">
  {% csrf_token %}

    <div class="form-group">
      <label for="id_username" class="col-sm-4 control-label">Username</label>
      <div class="col-sm-4">
        <div class="input-group">
          <div class="input-group-addon">required</div>
          <input class="form-control" name="username" id="id_username" type="text" size="30" value="{% if username %}{{username}}{% endif %}" aria-describedby="helpUsername" />
        </div>
        <span id="helpUsername" class="help-block">Please enter your desired username</span>
      </div>
    </div>

    <div class="form-group">
      <label for="id_email" class="col-sm-4 control-label">Email</label>
      <div class="col-sm-4">
        <div class="input-group">
          <div class="input-group-addon">required</div>
          <input class="form-control" name="email" id="id_email" type="text" size="30" value="{% if email %}{{email}}{% endif %}" aria-describedby="helpEmail" />
        </div>
        <span id="helpEmail" class="help-block">Please enter your email address</span>
      </div>
    </div>

    <div class="form-group">
      <label for="id_token" class="col-sm-4 control-label">Token</label>
      <div class="col-sm-4">
        <div class="input-group">
          <div class="input-group-addon">required</div>
          <input class="form-control" name="token" id="id_token" type="text" size="30" value="{% if token %}{{token}}{% endif %}" aria-describedby="helpToken" />
        </div>
        <span id="helpToken" class="help-block">And also provide your invite token</span>
      </div>
    </div>

    <div class="form-group">
      <label for="id_languages" class="col-sm-4 control-label">Languages</label>
      <div class="col-sm-4">
        <div class="input-group">
          <div class="input-group-addon">required</div>
          <select class="form-control" name="languages" id="id_languages" multiple="multiple">
{% for code, name in language_choices %}
            <option {% if code in languages %}selected="selected"{% endif %}value="{{code}}">{{name}}</option>
{% endfor %}
          </select>
        </div>
        <span id="helpLanguages" class="help-block">Which languages will you evaluate?</span>
      </div>
    </div>

    <button type="submit" class="col-sm-offset-4 btn btn-primary">Create profile</button>

  </form>
{% endblock %}

{% block actions %}
    <script>
  {% if focus_input %}
      // Set focus to given input
      $('#{{ focus_input }}').focus();
  {% else %}
      // by default, set focus on username input
      $('#id_username').focus();
  {% endif %}
    </script>
{% endblock %}

Dashboard/templates/Dashboard/group-status.html
{% extends 'Dashboard/base.html' %}
{% load humanize %}

{% block content %}
  <div class="page-header">
    <h1>Group status</h1>
    <p>Computed based on all completed annotation tasks.</p>

    <table class="table table-striped">
      <tr>
        <th>Group name</th><th>Completed tasks</th><th>Total tasks</th>
      </tr>
{% for item in group_status %}
      <tr>
        <td>{{item.0}}</td><td>{{item.1}}</td><td>{{item.2}}</td>
      </tr>
{% endfor %}
      <tr>
        <td>Total</td><td>{{sum_completed|intcomma}}</td><td>{{sum_total|intcomma}}</td>
      </tr>
    </table>
  </div>
{% endblock %}

Dashboard/templates/Dashboard/metrics-status.html
{% extends 'Dashboard/base.html' %}

{% block content %}
  <div class="page-header">
    <h1>Metrics status</h1>
    <p>Computed based on all completed annotation items.</p>

    <table class="table table-striped">
      <tr>
        <th>Task ID</th><th>Language pair</th><th>Annotators</th><th>Completed items</th>
      </tr>
{% for item in task_status %}
      <tr>
        <td>{{item.0}}</td><td>{{item.1}}-{{item.2}}</td><td>{{item.3}} ({{item.4}}%)</td><td>{{item.5}} ({{item.6}}%)</td>
      </tr>
{% endfor %}
    </table>
  </div>
{% endblock %}